const rootElement = 'fotorama'

export default {
    rootElement,
    _fullscreenClass: `${rootElement}-fullscreen`,
    wrapClass: `${rootElement}__wrap`,
    wrapVideoClass: `${rootElement}__wrap--video`,
    wrapFadeClass: `${rootElement}__wrap--fade`,
    wrapSlideClass: `${rootElement}__wrap--slide`,
    wrapNoControlsClass: `${rootElement}__wrap--no-controls`,
    wrapNoShadowsClass: `${rootElement}__wrap--no-shadows`,
    wrapRtlClass: `${rootElement}__wrap--rtl`,
    wrapOnlyActiveClass: `${rootElement}__wrap--only-active`,
    wrapNoCaptionsClass: `${rootElement}__wrap--no-captions`,
    wrapToggleArrowsClass: `${rootElement}__wrap--toggle-arrows`,
    stageClass: `${rootElement}__stage`,
    stageFrameClass: `${rootElement}__stage__frame`,
    stageFrameVideoClass: `${rootElement}__stage__frame--video`,
    stageShaftClass: `${rootElement}__stage__shaft`,
    grabClass: `${rootElement}__grab`,
    pointerClass: `${rootElement}__pointer`,
    arrClass: `${rootElement}__arr`,
    arrDisabledClass: `${rootElement}__arr--disabled`,
    arrPrevClass: `${rootElement}__arr--prev`,
    arrNextClass: `${rootElement}__arr--next`,
    navClass: `${rootElement}__nav`,
    navWrapClass: `${rootElement}__nav-wrap`,
    navShaftClass: `${rootElement}__nav__shaft`,
    navDotsClass: `${rootElement}__nav--dots`,
    navThumbsClass: `${rootElement}__nav--thumbs`,
    navFrameClass: `${rootElement}__nav__frame`,
    navFrameDotClass: `${rootElement}__nav__frame--dot`,
    navFrameThumbClass: `${rootElement}__nav__frame--thumb`,
    fadeClass: `${rootElement}__fade`,
    fadeFrontClass: `${rootElement}__fade-front`,
    fadeRearClass: `${rootElement}__fade-rear`,
    shadowClass: `${rootElement}__shadow`,
    shadowsClass: `${rootElement}__shadows`,
    shadowsLeftClass: `${rootElement}__shadow--left`,
    shadowsRightClass: `${rootElement}__shadow--right`,
    activeClass: `${rootElement}__active`,
    selectClass: `${rootElement}__select`,
    hiddenClass: `${rootElement}--hidden`,
    fullscreenClass: `${rootElement}--fullscreen`,
    fullscreenIconClass: `${rootElement}__fullscreen-icon`,
    errorClass: `${rootElement}__error`,
    loadingClass: `${rootElement}__loading`,
    loadedClass: `${rootElement}__loaded`,
    loadedFullClass: `${rootElement}__loaded--full`,
    loadedImgClass: `${rootElement}__loaded--img`,
    grabbingClass: `${rootElement}__grabbing`,
    imgClass: `${rootElement}__img`,
    imgFullClass: `${rootElement}__img--full`,
    dotClass: `${rootElement}__dot`,
    thumbClass: `${rootElement}__thumb`,
    thumbBorderClass: `${rootElement}__thumb-border`,
    htmlClass: `${rootElement}__html`,
    videoClass: `${rootElement}__video`,
    videoPlayClass: `${rootElement}__video-play`,
    videoCloseClass: `${rootElement}__video-close`,
    captionClass: `${rootElement}__caption`,
    captionWrapClass: `${rootElement}__caption__wrap`,
    spinnerClass: `${rootElement}__spinner`,
    buttonAttributes: `" tabindex:"0" role:"button`,
};
